### ISSUE TITLE
Repo / project restructurings

### ISSUE THREAD

**Issue by zspitz** [zspitz/ExpressionTreeVisualizer#99]
Before:

<del>

- [x] Can visualizers be written using .NET Core 3? This would allow #80 without Costura, and #51   
- [x] Can VS 2017 be supported this way? Do we need to?  
One possibility - multitarget .NET Framework and .NET Core; the .NET Framework version should be merged using Costura and packaged for VS 2017

</del>

ATM it seems that debugger-side dlls written in .NET Core for visualizers are not seen by Visual Studio. We'll have to do this in .NET Framework, and merge using Costura.

---

During repo restructure:

- [x] Expression test objects
  - [x] separate project within repo
  - [x] add wiki page on ExpressionTreeToString
  - [x] wrap as nuget package (#89)
    - [x] project url should point to above wiki page
  - [x] trivially enables #88 
- [x] move library into separate repo -> ExpressionTreeToString
  - [x] move Shared into ExpressionTreeToString
  - [x] use test objects library to run tests
  - [x] migrate to SDK project format; NRT
- [x] visualizer
  - [x] rename current repo, solution, projects to ExpressionTreeVisualizer
  - [x] remove Visualizer.2017; merge Visualizer.Shared and Visualizer.2019 into ExpressionTreeVisualizer
  - [x] migrate to SDK project format (#97); NRT
  - [x] split off debuggee code into separate projects
    - [x] build should go into [separate subfolders based on target framework](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-install-a-visualizer?view=vs-2019)
    - [x] ZIP up all files, preserving this subfolder structure
    - [x] For .NET Framework debuggee, use Costura to merge into a single DLL
    - [x] Check the possibility for other debuggee versions
  - [x] create solution for CI; will build and run tests but not the "playground" projects; modify `appveyor.yml`
    - [x] create a post-build project in the original solution, not the CI solution; copies the output DLLs to the relevant folders
  - [x] merge library dll using Costura
  - [x] use test objects library to run tests
- [x] migrate wiki to new repos
  - [x] add changelog, roadmap, solution structure, and contributing pages
- [x] <del>remove files from old repo; add links to new repos</del>

After:

- [x] visualizer
  - [x] separate ExpressionTreeControl (displays viewmodel) from VisualizerWindow (manages DataContext using TransferData)
    - [X] break dependency of Package project on Visualizer project; reference shared projects directly
  - [x] MVVM, then #79 can be done using the test object library
  - [X] deploy viewmodels + views (including serialization models) as Nuget package
    - [ ] <del>move all the code to a .NET Core 3.1 project (UI.Core); modifications made to this project</del>
    - [ ] <del>add a post-build step to copy all files into UI.Fx targeting .NET Framework</del>
    - [X] ideally, multitarget .NET Framework, .NET Core (.NET Standard?)
  - [ ] <del>remove dependency on MultiSelectTreeView</del> 
  - [x] create separate build output for VS 2019 -- ZIP file with subfolder structure for multiple frameworks -- and VS 2017 -- ZIP file with single dll
- [ ] Update external links -- RubberDuck, MS docs
  - [ ] `https://github.com/agileobjects/ReadableExpressions/issues/47`

---

Some more details:
```
domains:
serialization models
visualizer object source
view models + views
visualizer

visualizer:
serialization models into multitarget debuggee dlls
everything else into NET Framework debugger dll
	reference to some debuggee dll is required, for use of serialization models

wpf control library:
(deploy as nuget package)
serialization models + view models + views
	constructor for view model from actual type (not serialization model)

test projects reference wpf control library
	(it will have a dependency on WPF, use .NET Core 3)

**Comment by zspitz** [comment]
PR for MS Docs is [here](https://github.com/dotnet/docs/pull/18473).
